data:
gestao:
login: "LEANDRO"
senha: '2Le-SJ_8*cdf'
relatorio_sistema : C:\\arius-play\\arius_relatorio_erp\\img\\relatorios-do-sistema.PNG

usuarios: C:\\arius-play\\arius_relatorio_erp\\img\usuarios.PNG

compras: C:\\arius-play\\arius_relatorio_erp\\img\compras.PNG

preco: C:\\arius-play\\arius_relatorio_erp\\img\\preco.PNG

empresa: C:\\arius-play\\arius_relatorio_erp\\img\\empresa.PNG

seta: C:\\arius-play\\arius_relatorio_erp\\img\\seta.PNG

n_lancamento: C:\\arius-play\\arius_relatorio_erp\\img\\n_lancamento.PNG

empresa_2: C:\\arius-play\\arius_relatorio_erp\\img\\empresa-2.PNG